// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWnWxGITaESbdWWshlLVbTGAxputBv-B4',
    appId: '1:869005261360:web:78019137dce15936d80bf5',
    messagingSenderId: '869005261360',
    projectId: 'alejandriaapp',
    authDomain: 'alejandriaapp.firebaseapp.com',
    storageBucket: 'alejandriaapp.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkhOBKk316G24Oi4vhM2MRbAGDVX1mT8w',
    appId: '1:869005261360:android:73cb434d6da548f6d80bf5',
    messagingSenderId: '869005261360',
    projectId: 'alejandriaapp',
    storageBucket: 'alejandriaapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANz1MGteXQX-NIknrW12dza0Q2DYer71I',
    appId: '1:869005261360:ios:a4cf2236ef07b6dcd80bf5',
    messagingSenderId: '869005261360',
    projectId: 'alejandriaapp',
    storageBucket: 'alejandriaapp.appspot.com',
    iosClientId: '869005261360-fg9g6s4o6d385cldue9ikkvc0q77rc76.apps.googleusercontent.com',
    iosBundleId: 'com.example.alejandria',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANz1MGteXQX-NIknrW12dza0Q2DYer71I',
    appId: '1:869005261360:ios:a4cf2236ef07b6dcd80bf5',
    messagingSenderId: '869005261360',
    projectId: 'alejandriaapp',
    storageBucket: 'alejandriaapp.appspot.com',
    iosClientId: '869005261360-fg9g6s4o6d385cldue9ikkvc0q77rc76.apps.googleusercontent.com',
    iosBundleId: 'com.example.alejandria',
  );
}
